services:
  - type: web
    name: deltaelmechsystems-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    plan: free
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_API_URL
        value: https://deltaelmechsystems-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 